[workspace]
members = ["crates/*"]

[workspace.package]
description = "Kakarot is an (zk)-Ethereum Virtual Machine implementation written in Cairo."
documentation = "https://www.kakarot.org/"
cairo-version = "2.7.1"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/kkrt-labs/kakarot-ssj/"
license-file = "LICENSE"

[workspace.dependencies]
starknet = "2.7.1"
cairo_test = "2.7.1"
alexandria_macros = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[workspace.tool.fmt]
sort-module-level-items = true

[dev-dependencies]
cairo_test = "2.7.1"
