[package]
name = "contracts"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true
evm = { path = "../evm" }
openzeppelin = { path = "../openzeppelin" }
utils = { path = "../utils" }

[tool]
fmt.workspace = true

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true

[lib]
name = "contracts"

[dev-dependencies]
cairo_test = "2.7.0"
