[package]
name = "snforge_utils"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.7.1"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.28.0" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true


[lib]
name = "snforge_utils"

[scripts]
test = "snforge test"
