[package]
name = "evm"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet.workspace = true
utils = { path = "../utils" }
contracts = { path = "../contracts" }
openzeppelin = { path = "../openzeppelin" }
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }
snforge_utils = { path = "../snforge_utils" }
assert_macros = "0.1.0"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
build-external-contracts = [
  "openzeppelin::token::erc20::erc20::ERC20",
  "contracts::uninitialized_account::UninitializedAccount",
  "contracts::account_contract::AccountContract",
  "contracts::kakarot_core::kakarot::KakarotCore",
]


[lib]
name = "evm"
[tool]
fmt.workspace = true

[scripts]
test = "snforge test --max-n-steps 4294967295"
test-profiling = "snforge test --max-n-steps 4294967295 --build-profile"
